name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_docs:

    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build distribution
      run: python setup.py sdist bdist_wheel
    - name: Deploy
      run: twine upload -r pypi dist/*
      env:
        TWINE_USERNAME: ${{ secrets.DEPLOY_USER }}
        TWINE_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
