name: Docs

on: [push, pull_request, workflow_dispatch, release]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - uses: actions/setup-python@v2

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install
      
      - name: Get Previous Tag
        id: get_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0

      - name: Update Config Version
        run: |
          sed -i "s/0.0.0/${{ steps.get_tag.outputs.tag }}/" ./docs/conf.py

      - name: Sphinx Build
        run: |
          poetry run sphinx-build docs docs/_build

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && github.event.action == 'created')
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
